name: Build Debian Package

on:
  push:
    tags:
      - '*'

env:
  DEB_BUILD_OPTIONS: nocheck

jobs:
  build-artifact:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master

      - name: Install Debian Package Building Dependencies
        run: sudo bash debian/install_pkg_build_deps.sh

      - name: Create Debian Package
        run: make clean package

      - name: Upload Artifacts to GitHub
        uses: actions/upload-artifact@master
        with:
          name: artifact-deb
          path: deb_dist/*.deb

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset to GitHub
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: deb_dist/*.deb
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true